//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Data.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int IDCust { get; set; }
        public string DateFi { get; set; }
        public string NameCust { get; set; }
        public string AddrCust { get; set; }
        public string FloorCust { get; set; }
        public string apartCuat { get; set; }
        public string PhoneCust { get; set; }
        public string MobileCust { get; set; }
        public string MobilePlus { get; set; }
        public string TypeCust { get; set; }
        public string DetailsCust { get; set; }
    }
}
