//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Data.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryAreas
    {
        public int ID { get; set; }
        public string A_Name { get; set; }
        public decimal A_Price { get; set; }
        public string Note { get; set; }
    }
}
