//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Data.Database_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPEntities : DbContext
    {
        public ERPEntities()
            : base("name=ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Delevery> Deleverys { get; set; }
        public virtual DbSet<DeliveryArea> DeliveryAreas { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<ItemGroup> ItemGroups { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemsType> ItemsTypes { get; set; }
        public virtual DbSet<ItemsUnit> ItemsUnits { get; set; }
        public virtual DbSet<Keeper> Keepers { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<OutofStore> OutofStores { get; set; }
        public virtual DbSet<pricing> pricings { get; set; }
        public virtual DbSet<Return> Returns { get; set; }
        public virtual DbSet<ReturnsInvoice> ReturnsInvoices { get; set; }
        public virtual DbSet<Safe> Safes { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<Supply> Supplies { get; set; }
        public virtual DbSet<Tax> Taxs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WaitInvoice> WaitInvoices { get; set; }
        public virtual DbSet<PrintSetting> PrintSettings { get; set; }
    }
}
