//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Data.Database_Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPEntities : DbContext
    {
        public ERPEntities()
            : base("name=ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<ItemGroup> ItemGroup { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<pricing> pricing { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WaitInvoice> WaitInvoice { get; set; }
        public virtual DbSet<OutofStore> OutofStore { get; set; }
        public virtual DbSet<Supply> Supply { get; set; }
        public virtual DbSet<ReturnsInvoice> ReturnsInvoice { get; set; }
        public virtual DbSet<Returns> Returns { get; set; }
        public virtual DbSet<Stores> Stores { get; set; }
        public virtual DbSet<Safes> Safes { get; set; }
        public virtual DbSet<Branches> Branches { get; set; }
        public virtual DbSet<Deleverys> Deleverys { get; set; }
        public virtual DbSet<Keepers> Keepers { get; set; }
        public virtual DbSet<DeliveryAreas> DeliveryAreas { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Offers> Offers { get; set; }
        public virtual DbSet<Taxs> Taxs { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
    }
}
