//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Data.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int ID { get; set; }
        public string O_Name { get; set; }
        public Nullable<decimal> P_Quantity { get; set; }
        public Nullable<decimal> F_Quantity { get; set; }
        public bool IsFree { get; set; }
        public Nullable<decimal> CashBack { get; set; }
        public bool IsActive { get; set; }
        public string Note { get; set; }
    }
}
