//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Data.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutofStore
    {
        public int IDMove { get; set; }
        public Nullable<int> IDSell { get; set; }
        public string DateMove { get; set; }
        public int UserID { get; set; }
        public Nullable<int> CustID { get; set; }
        public int ItemID { get; set; }
        public decimal Amount { get; set; }
        public string TypeMove { get; set; }
        public string DetailsMove { get; set; }
    }
}
