//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Data.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintSetting
    {
        public int ID { get; set; }
        public string ReportName { get; set; }
        public string PaperSize { get; set; }
        public string NofCopies { get; set; }
        public string PrinterName { get; set; }
    }
}
