//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Data.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int IDMove { get; set; }
        public int InvoiceID { get; set; }
        public Nullable<int> WaitID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> CustID { get; set; }
        public string DateMove { get; set; }
        public Nullable<double> DaINT { get; set; }
        public int ItemID { get; set; }
        public decimal Quant { get; set; }
        public string UnitItem { get; set; }
        public string UnitPrice { get; set; }
        public decimal Price { get; set; }
        public decimal Total { get; set; }
        public string DetiMove { get; set; }
        public bool Return { get; set; }
    }
}
