//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Data.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int IDUser { get; set; }
        public string NameUser { get; set; }
        public string Pass { get; set; }
        public int Prmession { get; set; }
        public Nullable<int> LevelUser { get; set; }
        public int ActiveUser { get; set; }
        public string DetUser { get; set; }
    }
}
