//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Data.Database_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitInvoice
    {
        public int IDWait { get; set; }
        public int InvoiceID { get; set; }
        public string DateInv { get; set; }
        public Nullable<int> CustID { get; set; }
        public string TypInv { get; set; }
        public decimal NetBill { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> additional { get; set; }
        public Nullable<decimal> ShipPrice { get; set; }
        public decimal TotalInvo { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> TherRest { get; set; }
        public Nullable<int> DelvID { get; set; }
        public int UserID { get; set; }
        public string DetailsBill { get; set; }
    }
}
